// ===================الترجمه===============

const Translations = {
    ar: {
        pagetitle: 'شركة الصالح | للانشاء و التعمير',
        pagetitles:'شركة الصالح | خدماتنا',
        pagetitlep:'شركة الصالح | مشروعاتنا',
        navlink1: 'الصفحة الرئيسية',
        navlink2: 'خدمانتا',
        navlink3: 'مشاريعنا',
        navlink4: 'من نحن',
        navlink5: 'تواصل معنا',
        landingtitle: 'شركة الصالح للانشاءات',
        landingp: 'بناء بثقة وإتقان – نبني المستقبل بجودة وإتقان"',
        featurestitle: 'نحن لدينا الافضل',
        featuresp1: 'لدينا نخبة النخبة فى جميع التخصصات',
        featuresh41: 'تخطيط و تصميم',
        featuresp21: 'لدينا نخبة من افضل المهندسين المعماريين الذين صمموا افضل و افخم المبانى فى العالم وايضا يمتازون بالمخيله التى تكنهم من جعل تصورك واقع',
        featuresh42: 'بناء و تطبيق',
        featuresp22: 'لدينا نخبة من افضل المهندسين المعمارين الذين صمموا افضل و افخم المبانى فى العالم وايضا يمتازون بالمخيله التى تكنهم من جعل تصورك واقع',
        featuresh43: 'تشطيب و تسليم',
        featuresp23: 'لدينا نخبة من افضل المهندسين المعمارين الذين صمموا افضل و افخم المبانى فى العالم وايضا يمتازون بالمخيله التى تكنهم من جعل تصورك واقع',
        ourworktitle: 'مشروعاتنا',
        ourworkp: 'نحن نصنع الفخامه شاهد اعمالنا',
        li1: 'الكل',
        li2: 'تصاميمنا',
        li3: 'مشروعاتنا',
        li4: 'صور',
        li5: 'فديوهات',
        ourworkbtn: 'شاهد المزيد',
        stufftitle: 'من نحن',
        stuffp1: 'نحب ما نعمل',
        stuffp2: 'نحن نقوم بعملنا بحب لان الانشاء و البناء شى جميل نحب القيام به و نقوم به بالتزام و تفانى',
        stufftitle2: 'تصاميم الصالح ',
        stuffp3: 'نحن نقوم بعملنا بحب لان الانشاء و البناء شى جميل نحب القيام به و نقوم به بالتزام و تفانى',
        stuffp4: 'نحن نقوم بعملنا بحب لان الانشاء و البناء شى جميل نحب  القيام به و نقوم به بالتزام و تفانى نحن نقوم بعملنا بحب لان الانشاء و البناء شى جميل نحب  القيام به و نقوم به بالتزام و تفانى',
        stuffbtn: 'اطلب خدماتنا الان',
        teamtitle: 'قابل فريق النخبة لدينا',
        teamp: 'ليس هذا كل ما لدينا هؤلاء هم النخبة نتيجة التصويت داخل مجموعة شركاتنا بناء على مجهودهم',
        teamname1: 'مهندس مدنى ادهم',
        teamp1: 'افضل تصميم فى افريقا لدار الاوبرا فى  تنزانيا',
        teamname2: 'مهندس مدنى ادهم',
        teamp2: 'افضل تصميم فى افريقا لدار الاوبرا فى  تنزانيا',
        teamname3: 'مهندس مدنى ادهم',
        teamp3: 'افضل تصميم فى افريقا لدار الاوبرا فى  تنزانيا',
        teamname4: 'مهندس مدنى ادهم',
        teamp4: 'افضل تصميم فى افريقا لدار الاوبرا فى  تنزانيا',
        projecttitle: 'أبداء مشروعك معنا الان',
        projectp: 'ابداء ببناء احلامك معنا الان نقدم افضل خطط السداد و اقل الاسعار و بتسهيلات كثيرة',
        projectbtn: 'ابداء الان',
        blogtitle: 'اطلع على مدونتنا',
        blogp: 'مزيد من الاخبار',
        blogh51: 'اخر اخبار سوق العقارات',
        blogh52: 'اخر اخبار سوق العقارات',
        blogh53: 'اخر اخبار سوق العقارات',
        blogbtn: 'المزيد من الاخبار',
        footerp1: '" بناء بثقة وإتقان – نبني المستقبل بجودة وإتقان"',
        footerlink0: 'روابط',
        footerlink1: 'الصفحة الرئيسية',
        footerlink2: 'خدماتنا',
        footerlink3: 'مشروعاتنا',
        footerlink4: 'من نحن',
        footerlink5: 'تواصل معنا',
        footerblog0: 'مدونتنا',
        footerblog1: 'أخبار',
        footerblog2: 'فديوهات',
        footerblog3: 'صور',
        footerblog4: 'فريق العمل',
        footerblog5: 'شركائنا',
        footercontacth5: 'إتصل بنا',
        footercontactp: 'لا تتاخر فى الاستفسار عن اى شئ الرد يكون خلال 24 ساعة',
        footercontactbtn: 'ادخل بريد الالكترونى',
        h3pro:'دار الأوبرا في تنزانيا – تحفة معمارية من تصميم شركة الصالح',
        ppro1:'تفخر شركة "الصالح" بتقديم أحد أكثر مشاريعها تميزًا في قلب تنزانيا – دار الأوبرا الحديثة التي تجسد الإبداع المعماري والابتكار الهندسي. يجمع هذا الصرح الفريد بين التصميم الديناميكي والأداء الوظيفي، مما يجعله مركزًا ثقافيًا عالميًا يحتضن الفنون والموسيقى بأبهى صورها.استوحي التصميم من الطبيعة الأفريقية الغنية، حيث تعكس المنحنيات الانسيابية للمبنى حركة الأمواج وتناغم الموسيقى، مما يمنح الزوار تجربة حسية فريدة. بفضل استخدام أحدث التقنيات في البناء وهندسة الصوتيات، توفر دار الأوبرا تجربة استماع مثالية للجمهور، مما يجعل كل عرض فيها تجربة لا تُنسى.حرصت شركة "الصالح" على تحقيق الاستدامة في هذا المشروع من خلال استخدام مواد صديقة للبيئة وتقنيات حديثة لتوفير الطاقة، مما يعكس التزامنا بتقديم تصاميم معمارية مسؤولة بيئيًا. كما يضم المبنى مساحات متعددة الاستخدام، بما في ذلك قاعات للحفلات الموسيقية، ومسارح، ومرافق ترفيهية تواكب أعلى المعايير العالمية.نحن في "الصالح" نؤمن بأن الهندسة المعمارية ليست مجرد بناء، بل هي فن يروي قصة ويترك بصمة في المستقبل. ودار الأوبرا في تنزانيا هي دليل آخر على قدرتنا على تحويل الأحلام إلى واقع، مع تقديم تصاميم تلهم الأجيال القادمة.',
        h3pro2:'مسجد السلام – الإمارات العربية المتحدة',
        ppro2:'في قلب الإمارات العربية المتحدة، يبرز مسجد السلام كواحد من أروع المشاريع الدينية الحديثة، حيث يجمع بين الأصالة الإسلامية والتصميم المعماري المعاصر. مستوحى من الطراز العثماني، يتميز المسجد بقبابه الذهبية التي تتلألأ تحت أشعة الشمس، ومآذنه الشاهقة التي تعكس روحانية المكان. المدخل الرئيسي مزين بأقواس أنيقة ونقوش إسلامية دقيقة تضفي على المكان طابعًا فاخرًا ومهيبًا. يحيط بالمسجد ساحة واسعة مزودة بأرضيات رخامية تعكس جمال البناء، مما يجعلها مثالية للصلاة في الهواء الطلق.أحد أبرز عناصر التصميم هو الإضاءة المتدرجة التي تعكس الإبداع الهندسي، خاصة عند الغروب حيث تمتزج الأضواء الدافئة مع لون السماء الساحر. تم بناء المسجد باستخدام أحدث التقنيات لضمان الاستدامة البيئية، بما في ذلك أنظمة الإضاءة الذكية والتكييف الموفر للطاقة. يعد المسجد معلمًا دينيًا وثقافيًا، يجذب الزوار من مختلف أنحاء العالم، حيث لا يقتصر دوره على كونه مكانًا للصلاة، بل يُعد مركزًا لنشر المعرفة الإسلامية وتعزيز التواصل بين الثقافات. إن هذا المشروع يعكس رؤية الإمارات في المزج بين التراث والحداثة، ليصبح المسجد رمزًا للسلام والتسامح الديني.',
        h3pro3:'مجمع الصالح السكني – ألمانيا',
        ppro3:'يُعد مجمع الصالح السكني في ألمانيا نموذجًا رائعًا للعمارة الحديثة التي تدمج بين الأناقة والاستدامة. تم تصميم هذا المشروع ليواكب أعلى معايير البناء الأوروبية، حيث يعتمد على مواد صديقة للبيئة وتقنيات متطورة لتحسين كفاءة الطاقة. يتميز المجمع بواجهاته الزجاجية الأنيقة، التي تسمح بدخول كمية كبيرة من الضوء الطبيعي، مما يساهم في خلق بيئة معيشية مريحة وصحية. الألوان الحيادية المستخدمة في التصميم تمنح المكان طابعًا عصريًا ومتناغمًا مع المشهد الحضري المحيط به.يضم المجمع وحدات سكنية بمساحات متنوعة تناسب مختلف الاحتياجات، مع شرفات واسعة توفر إطلالات رائعة على الحدائق والمساحات الخضراء. تم دمج المرافق الحديثة مثل النوادي الرياضية، والمساحات المخصصة للعب الأطفال، والمراكز التجارية الصغيرة، مما يجعل المجمع بيئة مثالية للعائلات والأفراد الباحثين عن الراحة والرفاهية. كما تم تصميم المساحات الداخلية بعناية، حيث تم دمج التكنولوجيا الذكية في كل وحدة سكنية، مما يوفر تجربة سكنية متكاملة ومريحة. يعد هذا المجمع نموذجًا للتخطيط العمراني الذكي الذي يجمع بين الجمال والوظائف العملية، مما يجعله من أكثر المشاريع السكنية جاذبية في ألمانيا.',
        h3pro4:'كمبوند الصالح الذهبي – كندا',
        ppro4:'يعتبر كمبوند الصالح الذهبي في كندا مشروعًا سكنيًا فاخرًا يجمع بين الحداثة والطبيعة. تم تصميم هذا الكمبوند باستخدام خامات راقية مثل الخشب والزجاج، مما يمنحه طابعًا دافئًا يتناغم مع الأجواء الطبيعية المحيطة. يتميز المبنى بتصميم عصري يجمع بين الأناقة والبساطة، حيث توفر الشرفات الواسعة إطلالات رائعة على الحدائق والمساحات المفتوحة.يضم الكمبوند مجموعة من المرافق الفاخرة، بما في ذلك حمامات سباحة، ومراكز للياقة البدنية، ومسارات مشي بين المساحات الخضراء، مما يعزز جودة الحياة اليومية للسكان. تم تصميم الوحدات السكنية بلمسات عصرية، حيث توفر مساحات مفتوحة، وإضاءة طبيعية، ونوافذ بانورامية تتيح للسكان الاستمتاع بجمال البيئة المحيطة. كما تم دمج التكنولوجيا الذكية في إدارة المنازل، مما يضمن الراحة والأمان للسكان.يعد هذا المشروع مثالًا رائعًا على كيفية دمج البيئة الطبيعية مع العمارة الحديثة، حيث يوفر بيئة سكنية مثالية للأفراد والعائلات الباحثين عن الهدوء والفخامة. موقع الكمبوند في كندا يجعله مثاليًا لمن يبحثون عن نمط حياة عصري وسط بيئة طبيعية خلابة، مما يجعله واحدًا من أبرز المشاريع السكنية في البلاد.',
        h3pro5:'مدينة الصالح الذكية (سنغافورة)',
        ppro5:'مجمع حضري مستدام على جزيرة صناعية بمساحة 12 كم²، يدمج بين الطبيعة والتكنولوجيا. يشمل ناطحات سحاب مغطاة بالغابات العمودية، وشبكة طرق تحت أرضية للسيارات ذاتية القيادة، وأنفاق لخدمات اللوجستيات الآلية. يعتمد المشروع على طاقة الرياح والمد والجزر، مع نظام إعادة تدوير مياه متكامل. صُممت المدينة لتكون نموذجاً للكثافة السكانية الذكية مع حفاظها على 60% من مساحتها كمناطق خضراء. مجمع حضري مستدام على جزيرة صناعية بمساحة 12 كم²، يدمج بين الطبيعة والتكنولوجيا. يشمل ناطحات سحاب مغطاة بالغابات العمودية، وشبكة طرق تحت أرضية للسيارات ذاتية القيادة، وأنفاق لخدمات اللوجستيات الآلية. يعتمد المشروع على طاقة الرياح والمد والجزر، مع نظام إعادة تدوير مياه متكامل. صُممت المدينة لتكون نموذجاً للكثافة السكانية الذكية مع حفاظها على 60% من مساحتها كمناطق خضراء.',
        h3pro6:'مجمع الصالح البيئي (النرويج)',
        ppro6:' أول مجمع سكني في العالم "ذو انبعاثات سالبة" في أوسلو، مبني بالكامل من الخشب المعاد تدويره ومواد خرسانية صديقة للبيئة. يحتوي على مولدات طاقة من مخلفات السكان، وحدائق عمودية تنقي الهواء، وأنظمة تكييف تعمل بالطاقة الحرارية الجوفية. حصل على تصنيف "LEED البلاتيني" كأعلى معايير الاستدامة.',
        h3pro7:'مجمع الصالح البيئي (النرويج)',
        ppro7:'يعتبر كمبوند الصالح الذهبي في كندا مشروعًا سكنيًا فاخرًا يجمع بين الحداثة والطبيعة. تم تصميم هذا الكمبوند باستخدام خامات راقية مثل الخشب والزجاج، مما يمنحه طابعًا دافئًا يتناغم مع الأجواء الطبيعية المحيطة. يتميز المبنى بتصميم عصري يجمع بين الأناقة والبساطة، حيث توفر الشرفات الواسعة إطلالات رائعة على الحدائق والمساحات المفتوحة.يضم الكمبوند مجموعة من المرافق الفاخرة، بما في ذلك حمامات سباحة، ومراكز للياقة البدنية، ومسارات مشي بين المساحات الخضراء، مما يعزز جودة الحياة اليومية للسكان. تم تصميم الوحدات السكنية بلمسات عصرية، حيث توفر مساحات مفتوحة، وإضاءة طبيعية، ونوافذ بانورامية تتيح للسكان الاستمتاع بجمال البيئة المحيطة. كما تم دمج التكنولوجيا الذكية في إدارة المنازل، مما يضمن الراحة والأمان للسكان.يعد هذا المشروع مثالًا رائعًا على كيفية دمج البيئة الطبيعية مع العمارة الحديثة، حيث يوفر بيئة سكنية مثالية للأفراد والعائلات الباحثين عن الهدوء والفخامة. موقع الكمبوند في كندا يجعله مثاليًا لمن يبحثون عن نمط حياة عصري وسط بيئة طبيعية خلابة، مما يجعله واحدًا من أبرز المشاريع السكنية في البلاد',
        h3pro8:'مجمع الصالح البيئي (النرويج)',
        ppro8:'يعتبر كمبوند الصالح الذهبي في كندا مشروعًا سكنيًا فاخرًا يجمع بين الحداثة والطبيعة. تم تصميم هذا الكمبوند باستخدام خامات راقية مثل الخشب والزجاج، مما يمنحه طابعًا دافئًا يتناغم مع الأجواء الطبيعية المحيطة. يتميز المبنى بتصميم عصري يجمع بين الأناقة والبساطة، حيث توفر الشرفات الواسعة إطلالات رائعة على الحدائق والمساحات المفتوحة.يضم الكمبوند مجموعة من المرافق الفاخرة، بما في ذلك حمامات سباحة، ومراكز للياقة البدنية، ومسارات مشي بين المساحات الخضراء، مما يعزز جودة الحياة اليومية للسكان. تم تصميم الوحدات السكنية بلمسات عصرية، حيث توفر مساحات مفتوحة، وإضاءة طبيعية، ونوافذ بانورامية تتيح للسكان الاستمتاع بجمال البيئة المحيطة. كما تم دمج التكنولوجيا الذكية في إدارة المنازل، مما يضمن الراحة والأمان للسكان.يعد هذا المشروع مثالًا رائعًا على كيفية دمج البيئة الطبيعية مع العمارة الحديثة، حيث يوفر بيئة سكنية مثالية للأفراد والعائلات الباحثين عن الهدوء والفخامة. موقع الكمبوند في كندا يجعله مثاليًا لمن يبحثون عن نمط حياة عصري وسط بيئة طبيعية خلابة، مما يجعله واحدًا من أبرز المشاريع السكنية في البلاد',
        abouth2:'شركة الصالح | للانشاء و التعمير',
        aboutp1:'شركة الصالح هي إحدى الشركات الرائدة في مجالات الإنشاءات والتصميم الهندسي والتشطيبات والديكورات، حيث انطلقت برؤية واضحة ترتكز على الجودة، الابتكار، والالتزام بالمواعيد. تأسست الشركة لتكون علامة فارقة في عالم البناء والتصميم، وقد استطاعت خلال سنوات قليلة أن ترسخ مكانتها كمزود موثوق لحلول متكاملة في قطاع التشييد، من الفكرة الأولية وحتى التسليم النهائي.',
        aboutp2:'تضم شركة الصالح نخبة من المهندسين والمصممين والخبراء، الذين يعملون بروح الفريق ويعتمدون على أحدث التقنيات العالمية، لضمان تقديم مشاريع تلبّي تطلعات العملاء وتتجاوز توقعاتهم. تؤمن الشركة بأن كل مشروع هو فرصة لإبداع قصة جديدة، تجمع بين الجمال والوظيفة، وبين المتانة والتفاصيل الراقية.',
        abouth3:'من أبرز مشاريع الصالح العملاقة التي أنجزت أو ما زالت قيد التنفيذ حول العالم:',
        aboutp3:'مدينة الصالح الذكية في منطقة الخليج، وهي مشروع عمراني متكامل يضم وحدات سكنية، مراكز تجارية، ومساحات خضراء تعتمد على الطاقة المتجددة.برج فيجن في وسط آسيا، وهو ناطحة سحاب حديثة بتصميم مستوحى من العمارة الإسلامية، تم تشييدها وفق أعلى معايير الاستدامة',
        aboutp4:'مجمع الريادة المالي في أوروبا، الذي يضم مجموعة من المقرات البنكية والمكاتب الفاخرة، بتصميم داخلي يعكس الذوق العربي الأصيل بأسلوب معاصر.منتجع الرمال الملكي في شمال أفريقيا، وهو مشروع سياحي فاخر على الطراز المغربي، يدمج بين الفخامة والهدوء والطبيعة',
        ourpart:'شركائنا',
        h4contact:'تواصل معنا',
        namecont:'اسمك',
        emailcont:'البريد الالكتروني',
        subcont:'الموضوع',
        masscont:'رسالتك',
        buttcont:'ارسل رسالتك',
        cardtitle:'شبكة التواصل الاجتماعي',
        card1:'رقم الهاتف',
        card2:'عنوانا',
        card3:'واتس اب',
        card4:'فيسبوك',
        card5:'تويتر',
        card6:'انستجرام',
        card7:'لينكد ان',
        card8:'تيك توك',
        card9:'يوتيوب',
        card10:'سناب شات',

    },
    en: {
        pagetitle: 'Al Saleh Company | for Construction and Development',
        pagetitles:'Al Saleh Company | Services',
        pagetitlep:'Al Saleh Company | Projects',
        navlink1: 'Home',
        navlink2: 'Our services',
        navlink3: 'Our projects',
        navlink4: 'About us',
        navlink5: 'Contact us',
        landingtitle: 'Al Saleh Construction Company',
        landingp: 'Building with confidence and mastery - We build the future with quality and mastery',
        featurestitle: 'We have the best',
        featuresp1: 'We have the elite of the elite in all specialties',
        featuresh41: 'Planning and design',
        featuresp21: 'We have a group of the best architects who have designed the best and most luxurious buildings in the world and who also have the imagination that enables them to make your vision a reality.',
        featuresh42: 'Build and implement',
        featuresp22: 'We have a group of the best architects who have designed the best and most luxurious buildings in the world and who also have the imagination that enables them to make your vision a reality.',
        featuresh43: 'Finishing and delivery',
        featuresp23: 'We have a group of the best architects who have designed the best and most luxurious buildings in the world and who also have the imagination that enables them to make your vision a reality.',
        ourworktitle: 'Our projects',
        ourworkp: 'We make luxury. See our work.',
        li1: 'All',
        li2: 'Our designs',
        li3: 'Our projects',
        li4: 'photos',
        li5: 'Videos',
        ourworkbtn: 'See More',
        stufftitle: 'About us',
        stuffp1: 'We love what we do',
        stuffp2: 'We do our work with love because construction is a beautiful thing that we love to do and we do it with commitment and dedication.',
        stufftitle2: 'Al Saleh Designs',
        stuffp3: 'We do our work with love because construction is a beautiful thing that we love to do and we do it with commitment and dedication.',
        stuffp4: 'We do our work with love because construction is a beautiful thing that we love to do and we do it with commitment and dedication.We do our work with love because construction is a beautiful thing that we love to do and we do it with commitment and dedication.',
        stuffbtn: 'Request our services now',
        teamtitle: 'Meet our elite team',
        teamp: 'This is not all we have. These are the elite as a result of voting within our group of companies based on their efforts.',
        teamname1: 'Civil Engineer Adham',
        teamp1: 'Best design in Africa for the Tanzania Opera House',
        teamname2: 'Civil Engineer Adham',
        teamp2: 'Best design in Africa for the Tanzania Opera House',
        teamname3: 'Civil Engineer Adham',
        teamp3: 'Best design in Africa for the Tanzania Opera House',
        teamname4: 'Civil Engineer Adham',
        teamp4: 'Best design in Africa for the Tanzania Opera House',
        projecttitle: 'Start your project with us now',
        projectp: 'Start building your dreams with us now. We offer the best payment plans, the lowest prices, and many facilities.',
        projectbtn: 'Start now',
        blogtitle: 'Check out our blog',
        blogp: 'More news',
        blogh51: 'Latest real estate market news',
        blogh52: 'Latest real estate market news',
        blogh53: 'Latest real estate market news',
        blogbtn: 'More news',
        footerp1: 'Building with confidence and mastery - We build the future with quality and mastery',
        footerlink0: 'Links',
        footerlink1: 'Home',
        footerlink2: 'Our services',
        footerlink3: 'Our projects',
        footerlink4: 'About us',
        footerlink5: 'Contact us',
        footerblog0: 'Our blog',
        footerblog1: 'News',
        footerblog2: 'Videos',
        footerblog3: 'photos',
        footerblog4: 'Work team',
        footerblog5: 'Our partners',
        footercontacth5: 'Contact us',
        footercontactp: 'Do not delay in inquiring about anything. The response will be within 24 hours.',
        footercontactbtn: 'Enter your email address',
        h3pro:' Tanzania Opera House – An Architectural Masterpiece by Al-Saleh Company',
        ppro1:' Al Saleh Company is proud to present one of its most distinguished projects in the heart of Tanzania – the modern opera house that embodies architectural creativity and engineering innovation. This unique edifice combines dynamic design with functional performance, making it a global cultural center that embraces the arts and music in their finest forms. The design is inspired by the rich African nature, where the building’s flowing curves reflect the movement of waves and the harmony of music, providing visitors with a unique sensory experience. Thanks to the use of the latest construction techniques and acoustics engineering, the opera house offers an ideal listening experience for the audience, making every performance an unforgettable experience. Al Saleh Company is committed to sustainability in this project by using environmentally friendly materials and modern energy-saving technologies, reflecting our commitment to providing environmentally responsible architectural designs. The building also includes multi-purpose spaces, including concert halls, theaters, and recreational facilities that meet the highest global standards. At Al Saleh Company, we believe that architecture is not just about building; it is an art that tells a story and leaves a mark on the future. The opera house in Tanzania is another testament to our ability to turn dreams into reality, offering designs that inspire future generations.',
        h3pro2:' Al-Salam Mosque – United Arab Emirates',
        ppro2:'Located in the heart of the United Arab Emirates, Al-Salam Mosque stands as one of the most stunning modern religious projects, blending Islamic heritage with contemporary architectural design. Inspired by Ottoman architecture, the mosque features golden domes that glisten under the sunlight and towering minarets that enhance its spiritual ambiance. The main entrance is adorned with elegant arches and intricate Islamic carvings, giving the mosque a majestic and luxurious feel. Surrounding the mosque is a vast courtyard with marble flooring, reflecting the beauty of the structure and providing a serene space for outdoor prayers.One of the most remarkable design elements is the gradient lighting, which creates a mesmerizing effect, especially at sunset when the warm lights blend with the sky’s colors. The mosque is built with state-of-the-art technology to ensure environmental sustainability, including energy-efficient lighting and cooling systems. It serves not only as a place of worship but also as a cultural and educational center, attracting visitors from around the world. This project embodies the UAE’s vision of merging tradition with modernity, making the mosque a symbol of peace and religious harmony.',
        h3pro3:'Al-Saleh Residential Complex – Germany',
        ppro3:'The Al-Saleh Residential Complex in Germany is a prime example of modern architecture that seamlessly integrates elegance with sustainability. Designed to meet the highest European construction standards, this project utilizes eco-friendly materials and advanced technologies to enhance energy efficiency. The complex features stylish glass facades that allow ample natural light to flood the interiors, creating a comfortable and healthy living environment. Neutral color tones add a contemporary touch that blends harmoniously with the urban landscape.The complex offers a variety of residential units catering to different needs, with spacious balconies providing scenic views of landscaped gardens and green spaces. It is equipped with modern amenities, including fitness centers, children’s play areas, and small retail spaces, making it an ideal environment for families and individuals seeking comfort and convenience. The interiors are meticulously designed, incorporating smart home technology to enhance the living experience. This complex exemplifies smart urban planning, where beauty meets functionality, making it one of the most attractive residential projects in Germany.',
        h3pro4:'Al-Saleh Golden Compound – Canada',
        ppro4:'The Al-Saleh Golden Compound in Canada is a luxurious residential project that harmonizes modernity with nature. Designed using premium materials such as wood and glass, it exudes a warm ambiance that complements the surrounding natural environment. The building features a contemporary design that combines elegance with simplicity, offering spacious balconies with stunning views of gardens and open spaces.The compound boasts a range of luxurious amenities, including swimming pools, fitness centers, and walking paths amidst lush greenery, enhancing the quality of daily life for residents. The residential units are designed with modern touches, providing open spaces, natural lighting, and panoramic windows that allow residents to enjoy the beauty of the surrounding environment. Smart technology is integrated into home management systems, ensuring comfort and security for residents. This project is a prime example of how to blend natural surroundings with modern architecture, providing an ideal living environment for individuals and families seeking tranquility and luxury. Its location in Canada makes it perfect for those looking for a contemporary lifestyle amidst breathtaking natural beauty, making it one of the most prominent residential projects in the country.',
        h3pro5:'Al Saleh Smart City (Singapore)',
        ppro5:'A sustainable urban complex on a 12-kilometer-square-meter artificial island, it combines nature and technology. It includes skyscrapers covered in vertical forests, an underground network for self-driving cars, and tunnels for automated logistics services. The project relies on wind and tidal energy, with an integrated water recycling system. The city is designed to be a model of smart population density while preserving 60% of its area as green spaces.',
        h3pro6:'Al-Saleh Environmental Complex (Norway)',
        ppro6:'The world\'s first "negative emissions" residential complex in Oslo, built entirely from recycled wood and eco-friendly concrete materials. It features energy generators from residents\' waste, vertical gardens that purify the air, and geothermal-powered cooling systems. It received the "LEED Platinum" rating for the highest sustainability standards.',
        h3pro7:'Al-Saleh Environmental Complex (Norway)',
        ppro7:'The Al-Saleh Residential Complex in Germany is a prime example of modern architecture that seamlessly integrates elegance with sustainability. Designed to meet the highest European construction standards, this project utilizes eco-friendly materials and advanced technologies to enhance energy efficiency. The complex features stylish glass facades that allow ample natural light to flood the interiors, creating a comfortable and healthy living environment. Neutral color tones add a contemporary touch that blends harmoniously with the urban landscape.The complex offers a variety of residential units catering to different needs, with spacious balconies providing scenic views of landscaped gardens and green spaces. It is equipped with modern amenities, including fitness centers, children’s play areas, and small retail spaces, making it an ideal environment for families and individuals seeking comfort and convenience. The interiors are meticulously designed, incorporating smart home technology to enhance the living experience. This complex exemplifies smart urban planning, where beauty meets functionality, making it one of the most attractive residential projects in Germany.',
        h3pro8:'Al-Saleh Environmental Complex (Norway)',
        ppro8:'The Al-Saleh Residential Complex in Germany is a prime example of modern architecture that seamlessly integrates elegance with sustainability. Designed to meet the highest European construction standards, this project utilizes eco-friendly materials and advanced technologies to enhance energy efficiency. The complex features stylish glass facades that allow ample natural light to flood the interiors, creating a comfortable and healthy living environment. Neutral color tones add a contemporary touch that blends harmoniously with the urban landscape.The complex offers a variety of residential units catering to different needs, with spacious balconies providing scenic views of landscaped gardens and green spaces. It is equipped with modern amenities, including fitness centers, children’s play areas, and small retail spaces, making it an ideal environment for families and individuals seeking comfort and convenience. The interiors are meticulously designed, incorporating smart home technology to enhance the living experience. This complex exemplifies smart urban planning, where beauty meets functionality, making it one of the most attractive residential projects in Germany.',
        abouth2:'Al Saleh Company | for Construction and Development',
        aboutp1:'Al Saleh Company is a leading company in the fields of construction, engineering design, finishing, and decoration. It was launched with a clear vision based on quality, innovation, and commitment to deadlines. Established to be a landmark in the world of construction and design, the company has, in just a few years, established itself as a reliable provider of integrated solutions in the construction sector, from the initial concept to final delivery.',
        aboutp2:'Al Saleh Company comprises a team of engineers, designers, and experts who work together as a team and utilize the latest global technologies to ensure projects meet and exceed client expectations. The company believes that every project is an opportunity to create a new story, combining beauty and function, durability and exquisite detail.',
        abouth3:'Among the most prominent mega projects of Al Saleh that have been completed or are still being implemented around the world:',
        aboutp3:'Al Saleh Smart City in the Gulf region is an integrated urban project that includes residential units, commercial centers, and green spaces that rely on renewable energy. Vision Tower in Central Asia is a modern skyscraper with a design inspired by Islamic architecture, built according to the highest sustainability standards.',
        aboutp4:'The European Financial Leadership Complex, which houses a group of banking headquarters and luxury offices, features an interior design that reflects authentic Arab taste with a contemporary style.The Royal Sands Resort in North Africa is a luxury Moroccan-style tourism project that combines luxury, tranquility, and nature.',
        ourpart:'Our part',
        h4contact:'Contact With Us',
        namecont:'Name',
        emailcont:'Email Address',
        subcont:'Subject',
        masscont:'Message',
        buttcont:'Send Message',
        cardtitle:'Our Social Media',
        card1:'Phone Number',
        card2:'Our Address',
        card3:"What's app",
        card4:'facebook',
        card5:'Twitter',
        card6:'Instagram',
        card7:'LinkedIn',
        card8:'TikTok',
        card9:'Youtube',
        card10:'Snapchat',
  
    }
};
const LangSelector = document.querySelector('select');
const bootstrapLtr = document.getElementById("bootstrapen");
const bootstrapRtl = document.getElementById("bootstrapar");

LangSelector.addEventListener('change', (Event) => {
    setLang(Event.target.value);
    localStorage.setItem("lang", Event.target.value);
});


document.addEventListener('DOMContentLoaded', () => {
    const language = localStorage.getItem("lang");
    setLang(language);
});
const setLang = (language) => {
    const elements = document.querySelectorAll('[data-itn]');
    elements.forEach((element) => {
        const Translationskey = element.getAttribute('data-itn');
        element.textContent = Translations[language][Translationskey];
    });

    document.dir = language === 'ar' ? "rtl" : 'ltr'
    LangSelector.addEventListener("change", function () {
        if (this.value === "ltr") {
            document.documentElement.setAttribute("dir", "rtl");
            document.documentElement.setAttribute("lang", "ar");
            bootstrapRtl.removeAttribute("disabled");
            bootstrapLtr.setAttribute("disabled", "true");
        } else if (this.value === "rtl") {
            document.documentElement.setAttribute("dir", "ltr");
            document.documentElement.setAttribute("lang", "en");
            bootstrapLtr.removeAttribute("disabled");
            bootstrapRtl.setAttribute("disabled", "true");
        }
    });

};